---

namespace: namespace-2-base

resources:
- namespace.yaml
- https://github.com/stakater/Reloader/deployments/kubernetes

patches:
# remove namespace from non-namespaced objects, which would throw error
- target:
    kind: "Cluster.*|ServiceAccount.*"
  patch: |-
    - op: remove
      path: /metadata/namespace
