applySpecVersion: 1
spec:
  configSync:
    enabled: true
    sourceFormat: unstructured
    syncRepo: https://github.com/AndreiMatrosau/gke-acm-environment-1.git
    syncBranch: main
    secretType: none
    syncWait: 5
    policyDir: acm-gke-repo/overlays/environment-1/cluster-1
    preventDrift: false
