applySpecVersion: 1
spec:
  configSync:
    enabled: true
    sourceFormat: unstructured
    syncRepo: https://github.com/andreimatrosau/gke-acm-environment-1.git
    syncBranch: main
    secretType: none
    policyDir: overlays/environment-1
    syncWait: 60
    policyController:
      enabled: false
    hierarchyController:
      enabled: false
