

resources:
- ../../../../base/app-1

namespace: namespace-app-1

# add annotation that allows configmap reloading
commonAnnotations:
  configmap.reloader.stakater.com/reload: nginx-cm

configMapGenerator:
- name: nginx-cm
  namespace: namespace-1
  behavior: replace
  files:
  - cm-index.html

generatorOptions:
  disableNameSuffixHash: true
